Vagrant.configure("2") do |config|
    config.vm.define "ebpf_test" do |vm|
        # Your configuration for the "ebpf_test" VM goes here
    end
    
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
    end

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y bpfcc-tools linux-headers-$(uname -r) build-essential
        sudo uname -a
    SHELL
end